# Generated by Django 5.1.3 on 2024-11-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='formations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
