# Generated by Django 5.1.3 on 2024-11-24 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_employe_competences_employe_formations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employe',
            name='competences',
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='employe',
            name='formations',
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.service'),
        ),
        migrations.AddField(
            model_name='employe',
            name='competences',
            field=models.ManyToManyField(related_name='employes', to='gestion.competence'),
        ),
        migrations.AddField(
            model_name='employe',
            name='formations',
            field=models.ManyToManyField(related_name='employes', to='gestion.formation'),
        ),
    ]
