# Generated by Django 5.1.3 on 2024-11-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_competence_formation_remove_employe_competences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='formations',
        ),
        migrations.DeleteModel(
            name='Competence',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
