# Generated by Django 5.1.3 on 2024-12-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_employe_competences_remove_employe_formations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_annuel', models.IntegerField(default=30, verbose_name='Solde de Congés Annuels')),
                ('solde_maladie', models.IntegerField(default=10, verbose_name='Solde de Congés Maladie')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='gestion.employe', verbose_name='Employé')),
            ],
        ),
    ]
