# Generated by Django 5.1.3 on 2024-12-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_employe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
    ]
