# Generated by Django 5.1.3 on 2025-01-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='salaire_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
