# Generated by Django 5.1.3 on 2025-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_employe_email_alter_salaire_salaire_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10),
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
