# Generated by Django 5.1.3 on 2025-01-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_customuser_department_customuser_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
