# Generated by Django 5.1.3 on 2025-01-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_employe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
