# Generated by Django 5.1.3 on 2025-01-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_employe_departement_employe_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='id_service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
