# Generated by Django 5.1.3 on 2025-01-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.employe'),
        ),
    ]
