# Generated by Django 5.1.3 on 2025-01-17 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_conge_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='gestion.employe'),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='gestion.employe'),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='solde_annuel',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='solde_maladie',
            field=models.IntegerField(default=10),
        ),
    ]
